name: Microblog image

on:
  push:
    branches:
      - main
    paths:
      - 'microblog/**'

steps:
  - name: Check out code
    uses: actions/checkout@v3

  - name: Build & push Docker image
    uses: mr-smithers-excellent/docker-build-push@v6
    with:
      image: sektasoldier/microblog
      tags: v1, latest
      dockerfile: Dockerfile.ci
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
