name: Microblog image

on:
  push:
    branches:
      - main
    paths:
      - 'microblog/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: sektasoldier/microblog
        tags: v1, latest
        registry: docker.io
        dockerfile: microblog/Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
